### ISSUE TITLE
Enable logging in the CC library

### ISSUE THREAD

**Issue by JeffBezos64** [jonathandunn/common_crawl_corpus#1]
Justification:
Logging is required to support debugging and track normal program execution. Using Pythons inbuilt logging functionality would enable downstream users (and us) to review a single log file to track task progress (through log propagation).

Delivery:
7/12

**Comment by nhanhuynh296** [comment]
Might need to refactor the code. There is duplicate codes within 2 files. Also, from [this answer](https://stackoverflow.com/a/36083311), our approach is a very bad practice.

**Comment by JeffBezos64** [comment]
Fair call, that is something to work on. Would be annoying for the user to have to deal with logs disappearing.
