### ISSUE TITLE
Deduplication - 1d hashing and pandas based methods

### ISSUE THREAD

**Issue by JeffBezos64** [jonathandunn/common_crawl_corpus#3]
Situation: 
Nathan is working on 1d hashing and pandas based methods. He intends to do a comparison of them to find the optimal method with a trade-off for time/space complexity.
Status:
Implemented, awaiting testing.

**Comment by nhanhuynh296** [comment]
Compared with using only text and hashed version, seemed like the hash version converted the text on to integers, which really speed up the performance.
